"""
sequence_converter.py
----------------------
مسئول تبدیل ستون‌های AUTO_INCREMENT در MySQL به GENERATED ... AS IDENTITY
در PostgreSQL، و همگام‌سازی (sync) مقدار sequence با بیشترین مقدار موجود
پس از انتقال داده‌ها.

نکته مهم: چون داده‌ها به صورت صریح (با مقدار اصلی ستون auto_increment) درج
می‌شوند، نیازی به تولید مقدار جدید توسط PostgreSQL در حین INSERT نیست. اما
باید GENERATED ... AS IDENTITY به صورت "GENERATED BY DEFAULT AS IDENTITY"
باشد (نه ALWAYS) تا امکان درج مقدار صریح وجود داشته باشد. سپس بعد از اتمام
انتقال داده، مقدار sequence باید به MAX(column)+1 تنظیم شود تا رکوردهای
بعدی که در آینده در برنامه واقعی درج می‌شوند، دچار تداخل کلید نشوند.
"""

from __future__ import annotations

import logging
from typing import List, Optional

from mysql_reader import ColumnInfo, TableSchema
from postgres_writer import PostgresWriter
from utils import safe_identifier


class SequenceConverter:
    """
    تولید DDL برای تبدیل ستون auto_increment به IDENTITY، و همگام‌سازی
    مقدار sequence بعد از migrate شدن داده‌ها.
    """

    def __init__(self, logger: logging.Logger):
        self.logger = logger

    def get_auto_increment_column(self, table_schema: TableSchema) -> Optional[ColumnInfo]:
        """ستون auto_increment جدول را برمی‌گرداند (در MySQL معمولاً حداکثر یکی وجود دارد)."""
        for column in table_schema.columns:
            if column.is_auto_increment:
                return column
        return None

    def build_identity_ddl(self, table_schema: TableSchema, pg_type: str) -> Optional[str]:
        """
        اگر جدول ستون auto_increment داشته باشد، DDL برای تبدیل آن به
        GENERATED BY DEFAULT AS IDENTITY تولید می‌کند.

        از "BY DEFAULT" به جای "ALWAYS" استفاده می‌شود تا در حین migration
        بتوانیم مقادیر اصلی را صریحاً درج کنیم؛ این با معماری این پروژه که
        PK ها بدون تغییر (INT/BIGINT ساده) منتقل می‌شوند سازگار است.
        """
        auto_inc_column = self.get_auto_increment_column(table_schema)
        if auto_inc_column is None:
            return None

        table_ident = safe_identifier(table_schema.name)
        col_ident = safe_identifier(auto_inc_column.name)

        return (
            f"ALTER TABLE {table_ident} "
            f"ALTER COLUMN {col_ident} ADD GENERATED BY DEFAULT AS IDENTITY"
        )

    def sync_sequence(
        self,
        writer: PostgresWriter,
        table_schema: TableSchema,
    ) -> Optional[str]:
        """
        بعد از migrate شدن داده‌های یک جدول، مقدار sequence مرتبط با ستون
        auto_increment را با MAX(column) موجود در جدول همگام می‌کند.
        اگر جدول ستون auto_increment نداشته باشد یا خالی باشد، هیچ کاری
        انجام نمی‌شود.

        خروجی: نام ستونی که sync شده (برای لاگ)، یا None.
        """
        auto_inc_column = self.get_auto_increment_column(table_schema)
        if auto_inc_column is None:
            return None

        max_value = writer.get_max_column_value(table_schema.name, auto_inc_column.name)
        if max_value is None:
            # جدول خالی است؛ نیازی به تنظیم sequence نیست (از مقدار پیش‌فرض 1 شروع می‌شود)
            self.logger.info(
                f"جدول '{table_schema.name}' خالی است؛ sequence ستون "
                f"'{auto_inc_column.name}' نیازی به sync ندارد."
            )
            return auto_inc_column.name

        writer.set_sequence_value(table_schema.name, auto_inc_column.name, max_value)
        self.logger.info(
            f"Sequence جدول '{table_schema.name}' برای ستون "
            f"'{auto_inc_column.name}' با مقدار {max_value} همگام‌سازی شد."
        )
        return auto_inc_column.name
